[package]
name = "specs-group-by"
version = "0.16.1"
authors = ["MrInformatic <maxundmoritz99199@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "0.16.1"
